name: captionwizand
train: False
evaluate: False
test: False
analyze_data: True

# dataset
dataset: vizwiz # mscoco, mscoco-karpathy, vizwiz
word_count_threshold: 5
max_length: 15

# model
extractor: inceptionv3
caption_model: show_att_tell #
embedding_dim: 256
units: 512
top_k_words: 7330

# trainer
batch_size: 64
buffer_size: 1000
epochs: 100
lr: 0.001
max_to_keep: 5
log_graphs: True
trainer_loglevel: debug
optimizer: adam
lr_decay: 0.1
lr_patience: 3
shuffle: True
restore: True
restart: 1e-10

# wandb
wandb:
  use: True
  project: vizwiz
  entity: captionwiz
