name: caption
train: Train
evaluate: False
test: True

# dataset
dataset: mscoco # mscoco, mscoco-karpathy, vizwiz

# model
extractor: inceptionv3
caption_model: show_att_tell #
embedding_dim: 256
units: 512
top_k_words: null
max_length: null

# trainer
batch_size: 64
buffer_size: 1000
epochs: 30
lr: 0.0001
max_to_keep: 5
log_graphs: True
trainer_loglevel: debug
optimizer: adam
lr_decay: 0.99
lr_patience: 3
shuffle: True

# wandb
wandb:
  use: True
  project: vizwiz
  entity: captionwiz
